### ISSUE TITLE
aws-s3-sink NoSuchMethodError with Kinesis binder

### ISSUE THREAD

**Issue by komushi** [spring-cloud-stream-app-starters/aws-s3#4]
aws-s3-sink fails to start up with spring-cloud-starter-stream-kinesis 1.0.0.M1.

```
2018-03-21 22:02:54.409  INFO 70083 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@75412c2f: startup date [Wed Mar 21 22:02:54 JST 2018]; root of context hierarchy
2018-03-21 22:02:54.682  INFO 70083 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$5cc8fd1c] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.0.RELEASE)

2018-03-21 22:02:54.881  INFO 70083 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8888
2018-03-21 22:02:54.964  WARN 70083 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/s3-sink/default": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)
2018-03-21 22:02:54.967  INFO 70083 --- [           main] o.s.c.s.a.s.s.r.S3SinkRabbitApplication  : No active profile set, falling back to default profiles: default
2018-03-21 22:02:54.980  INFO 70083 --- [           main] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@2f686d1f: startup date [Wed Mar 21 22:02:54 JST 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@75412c2f
2018-03-21 22:02:58.396  INFO 70083 --- [           main] o.s.i.config.IntegrationRegistrar        : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
2018-03-21 22:02:58.651  INFO 70083 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'environmentWebEndpointExtension' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.actuate.autoconfigure.env.EnvironmentEndpointAutoConfiguration; factoryMethodName=environmentWebEndpointExtension; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/actuate/autoconfigure/env/EnvironmentEndpointAutoConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.cloud.autoconfigure.LifecycleMvcEndpointAutoConfiguration$EndpointConfiguration; factoryMethodName=environmentWebEndpointExtension; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/cloud/autoconfigure/LifecycleMvcEndpointAutoConfiguration$EndpointConfiguration.class]]
2018-03-21 22:02:58.946  INFO 70083 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=6e87ca60-9e20-3925-935e-01a5aca5d709
2018-03-21 22:02:59.491  INFO 70083 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
2018-03-21 22:02:59.492  INFO 70083 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'taskScheduler' has been explicitly defined. Therefore, a default ThreadPoolTaskScheduler will be created.
2018-03-21 22:02:59.547  INFO 70083 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.amqp.rabbit.annotation.RabbitBootstrapConfiguration' of type [org.springframework.amqp.rabbit.annotation.RabbitBootstrapConfiguration$$EnhancerBySpringCGLIB$$71ab84d] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-03-21 22:02:59.609  INFO 70083 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.integration.config.IntegrationManagementConfiguration' of type [org.springframework.integration.config.IntegrationManagementConfiguration$$EnhancerBySpringCGLIB$$aba0b54e] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-03-21 22:02:59.621  INFO 70083 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$5cc8fd1c] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-03-21 22:02:59.917  INFO 70083 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8050 (http)
2018-03-21 22:02:59.942  INFO 70083 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2018-03-21 22:02:59.942  INFO 70083 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.28
2018-03-21 22:02:59.951  INFO 70083 --- [ost-startStop-1] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/Users/lleixu/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
2018-03-21 22:03:00.028  INFO 70083 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2018-03-21 22:03:00.028  INFO 70083 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 5048 ms
2018-03-21 22:03:00.869  INFO 70083 --- [ost-startStop-1] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService  'taskScheduler'
2018-03-21 22:03:01.278  INFO 70083 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2018-03-21 22:03:01.278  INFO 70083 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2018-03-21 22:03:01.279  INFO 70083 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2018-03-21 22:03:01.279  INFO 70083 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2018-03-21 22:03:01.279  INFO 70083 --- [ost-startStop-1] .s.DelegatingFilterProxyRegistrationBean : Mapping filter: 'springSecurityFilterChain' to: [/*]
2018-03-21 22:03:01.279  INFO 70083 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpTraceFilter' to: [/*]
2018-03-21 22:03:01.279  INFO 70083 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'webMvcMetricsFilter' to: [/*]
2018-03-21 22:03:01.280  INFO 70083 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Servlet dispatcherServlet mapped to [/]
2018-03-21 22:03:01.871  INFO 70083 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@2f686d1f: startup date [Wed Mar 21 22:02:54 JST 2018]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@75412c2f
2018-03-21 22:03:01.957  INFO 70083 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2018-03-21 22:03:01.958  INFO 70083 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2018-03-21 22:03:02.018  INFO 70083 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2018-03-21 22:03:02.018  INFO 70083 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2018-03-21 22:03:02.092  INFO 70083 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2018-03-21 22:03:02.625  INFO 70083 --- [           main] .s.s.UserDetailsServiceAutoConfiguration : 

Using generated security password: 03637bdf-a9e9-4052-9eec-947788d9d855

2018-03-21 22:03:02.803  INFO 70083 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: org.springframework.security.web.util.matcher.AnyRequestMatcher@1, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@3b96c42e, org.springframework.security.web.context.SecurityContextPersistenceFilter@5505ae1a, org.springframework.security.web.header.HeaderWriterFilter@291a7e3c, org.springframework.security.web.csrf.CsrfFilter@4716be8b, org.springframework.security.web.authentication.logout.LogoutFilter@512baff6, org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter@35432107, org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter@4ae9cfc1, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@61544ae6, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@21337f7b, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@60df60da, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@5d066c7d, org.springframework.security.web.session.SessionManagementFilter@1046d517, org.springframework.security.web.access.ExceptionTranslationFilter@6af9fcb2, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@5f9be66c]
2018-03-21 22:03:02.915  INFO 70083 --- [           main] s.b.a.e.w.s.WebMvcEndpointHandlerMapping : Mapped "{[/actuator/health],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$OperationHandler.handle(javax.servlet.http.HttpServletRequest,java.util.Map<java.lang.String, java.lang.String>)
2018-03-21 22:03:02.915  INFO 70083 --- [           main] s.b.a.e.w.s.WebMvcEndpointHandlerMapping : Mapped "{[/actuator/info],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$OperationHandler.handle(javax.servlet.http.HttpServletRequest,java.util.Map<java.lang.String, java.lang.String>)
2018-03-21 22:03:02.916  INFO 70083 --- [           main] s.b.a.e.w.s.WebMvcEndpointHandlerMapping : Mapped "{[/actuator],methods=[GET],produces=[application/vnd.spring-boot.actuator.v2+json || application/json]}" onto protected java.util.Map<java.lang.String, java.util.Map<java.lang.String, org.springframework.boot.actuate.endpoint.web.Link>> org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping.links(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2018-03-21 22:03:03.101  INFO 70083 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2018-03-21 22:03:03.109  INFO 70083 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'rabbitConnectionFactory' has been autodetected for JMX exposure
2018-03-21 22:03:03.110  INFO 70083 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'integrationMbeanExporter' has been autodetected for JMX exposure
2018-03-21 22:03:03.111  INFO 70083 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'configurationPropertiesRebinder' has been autodetected for JMX exposure
2018-03-21 22:03:03.112  INFO 70083 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'environmentManager' has been autodetected for JMX exposure
2018-03-21 22:03:03.113  INFO 70083 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Bean with name 'refreshScope' has been autodetected for JMX exposure
2018-03-21 22:03:03.115  INFO 70083 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'environmentManager': registering with JMX server as MBean [org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager]
2018-03-21 22:03:03.138  INFO 70083 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'refreshScope': registering with JMX server as MBean [org.springframework.cloud.context.scope.refresh:name=refreshScope,type=RefreshScope]
2018-03-21 22:03:03.151  INFO 70083 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'integrationMbeanExporter': registering with JMX server as MBean [org.springframework.integration.monitor:name=integrationMbeanExporter,type=IntegrationMBeanExporter]
2018-03-21 22:03:03.179  INFO 70083 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=2f686d1f,type=ConfigurationPropertiesRebinder]
2018-03-21 22:03:03.190  INFO 70083 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Located managed bean 'rabbitConnectionFactory': registering with JMX server as MBean [org.springframework.amqp.rabbit.connection:name=rabbitConnectionFactory,type=CachingConnectionFactory]
2018-03-21 22:03:03.204  INFO 70083 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering beans for JMX exposure on startup
2018-03-21 22:03:03.205  INFO 70083 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering MessageChannel input
2018-03-21 22:03:03.207  INFO 70083 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Located managed bean 'org.springframework.integration:type=MessageChannel,name=input': registering with JMX server as MBean [org.springframework.integration:type=MessageChannel,name=input]
2018-03-21 22:03:03.235  INFO 70083 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering MessageChannel errorChannel
2018-03-21 22:03:03.237  INFO 70083 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Located managed bean 'org.springframework.integration:type=MessageChannel,name=errorChannel': registering with JMX server as MBean [org.springframework.integration:type=MessageChannel,name=errorChannel]
2018-03-21 22:03:03.257  INFO 70083 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering MessageChannel nullChannel
2018-03-21 22:03:03.258  INFO 70083 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Located managed bean 'org.springframework.integration:type=MessageChannel,name=nullChannel': registering with JMX server as MBean [org.springframework.integration:type=MessageChannel,name=nullChannel]
2018-03-21 22:03:03.267  INFO 70083 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering MessageHandler errorLogger
2018-03-21 22:03:03.269  INFO 70083 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Located managed bean 'org.springframework.integration:type=MessageHandler,name=errorLogger,bean=internal': registering with JMX server as MBean [org.springframework.integration:type=MessageHandler,name=errorLogger,bean=internal]
2018-03-21 22:03:03.284  INFO 70083 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Registering MessageHandler org.springframework.cloud.stream.app.s3.sink.AmazonS3SinkConfiguration.amazonS3MessageHandler.serviceActivator
2018-03-21 22:03:03.285  INFO 70083 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Located managed bean 'org.springframework.integration:type=MessageHandler,name=org.springframework.cloud.stream.app.s3.sink.AmazonS3SinkConfiguration.amazonS3MessageHandler.serviceActivator,bean=endpoint': registering with JMX server as MBean [org.springframework.integration:type=MessageHandler,name=org.springframework.cloud.stream.app.s3.sink.AmazonS3SinkConfiguration.amazonS3MessageHandler.serviceActivator,bean=endpoint]
2018-03-21 22:03:03.295  INFO 70083 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase -2147483648
2018-03-21 22:03:03.296  INFO 70083 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {message-handler:org.springframework.cloud.stream.app.s3.sink.AmazonS3SinkConfiguration.amazonS3MessageHandler.serviceActivator} as a subscriber to the 'input' channel
2018-03-21 22:03:03.296  INFO 70083 --- [           main] o.s.integration.channel.DirectChannel    : Channel 'application-1.input' has 1 subscriber(s).
2018-03-21 22:03:03.296  INFO 70083 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started org.springframework.cloud.stream.app.s3.sink.AmazonS3SinkConfiguration.amazonS3MessageHandler.serviceActivator
2018-03-21 22:03:03.296  INFO 70083 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase -2147482648
2018-03-21 22:03:03.296  INFO 70083 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2018-03-21 22:03:03.297  INFO 70083 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2018-03-21 22:03:03.297  INFO 70083 --- [           main] o.s.i.channel.PublishSubscribeChannel    : Channel 'application-1.errorChannel' has 1 subscriber(s).
2018-03-21 22:03:03.297  INFO 70083 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started _org.springframework.integration.errorLogger
2018-03-21 22:03:03.297  INFO 70083 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 2147482647
2018-03-21 22:03:03.347  INFO 70083 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at: http://localhost:8888
2018-03-21 22:03:03.352  WARN 70083 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:8888/s3-sink/default": Connection refused (Connection refused); nested exception is java.net.ConnectException: Connection refused (Connection refused)
2018-03-21 22:03:03.357  INFO 70083 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@4c51cf28: startup date [Wed Mar 21 22:03:03 JST 2018]; parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@2f686d1f
2018-03-21 22:03:08.487  INFO 70083 --- [           main] o.s.c.s.b.k.p.KinesisStreamProvisioner   : Using Kinesis stream for inbound: filtered_geojson
2018-03-21 22:03:13.209  WARN 70083 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'inputBindingLifecycle'; nested exception is java.lang.NoSuchMethodError: org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter.setCheckpointStore(Lorg/springframework/integration/metadata/MetadataStore;)V
2018-03-21 22:03:13.211  INFO 70083 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Unregistering JMX-exposed beans on shutdown
2018-03-21 22:03:13.211  INFO 70083 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Unregistering JMX-exposed beans
2018-03-21 22:03:13.212  INFO 70083 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: input
2018-03-21 22:03:13.212  INFO 70083 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: errorChannel
2018-03-21 22:03:13.212  INFO 70083 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: nullChannel
2018-03-21 22:03:13.212  INFO 70083 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: _org.springframework.integration.errorLogger.handler
2018-03-21 22:03:13.212  INFO 70083 --- [           main] o.s.i.monitor.IntegrationMBeanExporter   : Summary on shutdown: amazonS3MessageHandler
2018-03-21 22:03:13.212  INFO 70083 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2018-03-21 22:03:13.212  INFO 70083 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans
2018-03-21 22:03:13.213  INFO 70083 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2018-03-21 22:03:13.214  INFO 70083 --- [           main] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@4c51cf28: startup date [Wed Mar 21 22:03:03 JST 2018]; parent: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@2f686d1f
2018-03-21 22:03:13.217  INFO 70083 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2018-03-21 22:03:13.235  INFO 70083 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-03-21 22:03:13.240 ERROR 70083 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'inputBindingLifecycle'; nested exception is java.lang.NoSuchMethodError: org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter.setCheckpointStore(Lorg/springframework/integration/metadata/MetadataStore;)V
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:184) ~[spring-context-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:52) ~[spring-context-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:157) ~[spring-context-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:121) ~[spring-context-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:884) ~[spring-context-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:161) ~[spring-boot-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) ~[spring-context-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388) [spring-boot-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234) [spring-boot-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
	at org.springframework.cloud.stream.app.s3.sink.rabbit.S3SinkRabbitApplication.main(S3SinkRabbitApplication.java:29) [classes!/:2.0.0.BUILD-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [s3-sink-rabbit-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [s3-sink-rabbit-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [s3-sink-rabbit-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [s3-sink-rabbit-2.0.0.BUILD-SNAPSHOT.jar:2.0.0.BUILD-SNAPSHOT]
Caused by: java.lang.NoSuchMethodError: org.springframework.integration.aws.inbound.kinesis.KinesisMessageDrivenChannelAdapter.setCheckpointStore(Lorg/springframework/integration/metadata/MetadataStore;)V
	at org.springframework.cloud.stream.binder.kinesis.KinesisMessageChannelBinder.createConsumerEndpoint(KinesisMessageChannelBinder.java:196) ~[spring-cloud-stream-binder-kinesis-1.0.0.M1.jar!/:1.0.0.M1]
	at org.springframework.cloud.stream.binder.kinesis.KinesisMessageChannelBinder.createConsumerEndpoint(KinesisMessageChannelBinder.java:65) ~[spring-cloud-stream-binder-kinesis-1.0.0.M1.jar!/:1.0.0.M1]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:279) ~[spring-cloud-stream-2.0.0.BUILD-SNAPSHOT.jar!/:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:77) ~[spring-cloud-stream-2.0.0.BUILD-SNAPSHOT.jar!/:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:129) ~[spring-cloud-stream-2.0.0.BUILD-SNAPSHOT.jar!/:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:134) ~[spring-cloud-stream-2.0.0.BUILD-SNAPSHOT.jar!/:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:116) ~[spring-cloud-stream-2.0.0.BUILD-SNAPSHOT.jar!/:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binding.BindableProxyFactory.createAndBindInputs(BindableProxyFactory.java:234) ~[spring-cloud-stream-2.0.0.BUILD-SNAPSHOT.jar!/:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:52) ~[spring-cloud-stream-2.0.0.BUILD-SNAPSHOT.jar!/:2.0.0.BUILD-SNAPSHOT]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[na:1.8.0_161]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:1.8.0_161]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_161]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:47) ~[spring-cloud-stream-2.0.0.BUILD-SNAPSHOT.jar!/:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:31) ~[spring-cloud-stream-2.0.0.BUILD-SNAPSHOT.jar!/:2.0.0.BUILD-SNAPSHOT]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.0.4.RELEASE.jar!/:5.0.4.RELEASE]
	... 22 common frames omitted
```

**Comment by artembilan** [comment]
The `spring-cloud-starter-stream-kinesis 1.0.0.M1` is not compatible with the latest Spring Integration AWS.
You have to switch to the latest `BUILD-SNAPSHOT`.
The fix was done yesterday: https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/commit/060fbd22af343c39fd7589ef19bc170bfcfc33cb

I think that's the point how you catch that issue with wrong format: https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/issues/42. You just use incompatible versions!

I think we are going to release SI AWS 2.0 M2 and Kinesis Binder 1.0 M2 today or tomorrow. The this `aws-s3` project will be updated.

**Comment by komushi** [comment]
Thanks. I will wait for Kinesis 1.0.0.M2.
